language: android
jdk: oraclejdk7

cache:
  directories:
  - $HOME/.gradle/caches
 
android:
  components:
  - build-tools-22.0.1
  - android-15
  - extra-android-m2repository
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  # required libs for android build tools
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch yasm
  # Android NDK
  - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r8e-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-r8e-linux-x86.tar.bz2 -O ndk.tgz; fi
  - tar -xf ndk.tgz
  - rm ndk.tgz
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r8e
  - export NDK=`pwd`/android-ndk-r8e
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
install:
  - sh -c 'cd library-jni/jni/ && ./fetch.sh'
  - sh -c 'cd library-jni/jni && ./build_android.sh'
  - sh -c 'cd library-jni/jni && ndk-build'
  - rm -rf $NDK
  - rm -rf library-jni/jni
  - TERM=dumb ./gradlew build

