language: android
jdk: oraclejdk7
sudo: false

env:
  global:
    - NDK_VERSION=r10e

addons:
  apt:
    packages:
    - libgd2-xpm
    - ia32-libs
    - ia32-libs-multiarch
    - yasm
    - pkg-config
    - make
    - autoconf
    - libtool
    - make
    - autoconf-archive
    - automake

cache:
  directories:
  - $HOME/.gradle/caches
  - library-jni/jni/ffmpeg/.git
  - library-jni/jni/freetype2/.git
  - library-jni/jni/fribidi/.git
  - library-jni/jni/libass/.git
  - library-jni/jni/libyuv/.git
  - library-jni/jni/tropicssl/.git
  - library-jni/jni/vo-aacenc/.git
  - library-jni/jni/vo-amrwbenc/.git
  - library-jni/jni/x264/.git
 
android:
  components:
  - build-tools-22.0.1
  - android-15
  - extra-android-m2repository
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

before_install:
  # Android NDK
  - if [ `uname -m` = x86_64 ]; then wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86_64.bin -O ndk.bin; else wget http://dl.google.com/android/ndk/android-ndk-$NDK_VERSION-linux-x86.bin -O ndk.bin; fi
  - chmod a+x ndk.bin
  - ./ndk.bin | egrep -v ^Extracting
  - rm ndk.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
install:
  - sh -c 'cd library-jni/jni/ && ./fetch.sh'
  - sh -c 'cd library-jni/jni && ./build_android.sh'
  - sh -c 'cd library-jni/jni && ndk-build'
  - rm -rf $ANDROID_NDK_HOME
  - rm -rf library-jni/jni
  - TERM=dumb ./gradlew build

